# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias vi='vim'

if [[ "$OSTYPE" == "linux-gnu" ]]
then
    alias ls='ls --color=tty'
    alias ll='ls -la --color=tty'
    alias l.='ls -d .* --color=tty'
    alias which='alias | /usr/bin/which'
else
    alias ls='ls -G'
    alias ll='ls -la -G'
    alias l.='ls -d .* -G'
fi

alias egrep="egrep --color"
alias grep="grep --color"
#alias rz='lrz -br'
#alias sz='lsz -br'

# Tahoe
alias t='tahoe -d $HOME/.tahoe'
alias tw='tahoe -d $HOME/.tahoe webopen'
alias tp='tahoe -d $HOME/.tahoe-private'
alias tpw='tahoe -d $HOME/.tahoe-private webopen'

# Dark
alias s='export HISTFILE=/dev/null && exit' # no bash history
alias lk='sudo logkeys -s -d /dev/input/event5 -o /var/log/logkeys.log' # start logkeys
alias unlk='sudo logkeys -k >/dev/null 2>&1' # stop logkeys
alias lkv='sudo logkeys -s -d /dev/input/event5 -o /var/log/logkeys.log ; sleep 1 ; pslk' # start logkeys (verbose check)
alias unlkv='sudo logkeys -k ; sleep 1 ; pslk' # stop logkeys (verbose check - only display if already stopped)
alias pslk='ps -ef | grep [l]ogkeys'
alias catlk='sudo cat /var/log/logkeys.log'
alias taillk='sudo tail -n 100 -f /var/log/logkeys.log'
alias vilk='sudo vi /var/log/logkeys.log'
alias rmlk='sudo rm -f /var/log/logkeys.log'

# Def
inversor() {
    # Dividir a saida em linhas invertidas:
    rev | while read linha; do
        # Dividir cada linha invertida em colunas:
        for cn in `echo $linha`; do
            # Mostrar coluna, desinvertendo suas letras
            echo -n `echo $cn | rev`
            # Dar espaco
            echo -n " "
        done

        # pular linha
        echo ""
    done
}

# Bash
source "$HOME/.bash_completion_funcs"
export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
export SYSTERM="linux"
export SYSFONT="lat1u-16"
export LC_COLLATE="POSIX"
export LS_COLORS="$LS_COLORS:di=01;33:*.rpm=01;31"
export LS_COLORS=$(echo $LS_COLORS | sed 's/00;31/01;31/g')
export HOSTNAME=$(echo "${HOSTNAME}" | cut -d. -f 1)
export EDITOR="vim"
export HISTTIMEFORMAT="%a %b %d %H:%M:%S %Z %Y - "
export HISTFILESIZE=99999
export HISTSIZE=99999
export PS1='\t \u@\h \w \$ '

# Path
export PATH="$PATH:/opt/local/bin:/opt/local/sbin"
export PATH="$PATH:/Users/stockrt/Dropbox/stockrt/scripts"
export PATH="$PATH:/usr/local/mysql/bin"

# Go
export GOPATH="$HOME/go"
export PATH="$PATH:$HOME/go/bin"

# Android
export ANDROID_HOME="$HOME/android/android-sdk"
export PATH="$PATH:$HOME/android/android-sdk/build-tools/21.1.1"
export PATH="$PATH:$HOME/android/android-sdk/platform-tools"
export PATH="$PATH:$HOME/android/android-sdk/tools"
export PATH="$PATH:$HOME/android/android-studio/bin"
export PATH="$PATH:$HOME/android/android-ndk-r10d"

# Java
export JAVA_HOME="/opt/java"
export PATH="$PATH:/opt/java/bin"
export PATH="$PATH:/opt/apache-ant/bin"
export PATH="$PATH:/opt/apache-maven/bin"
export PATH="$PATH:$HOME/eclipse"

# Node
export PATH="$PATH:$HOME/node_modules/.bin"
export PATH="$PATH:$HOME/node/bin"

# Python
export PATH="/usr/python27/bin:/usr/python26/bin:$PATH"
alias pa='source "$HOME/.virtualenvs/venv/bin/activate" ; source "$HOME/.virtualenvs/venv/bin/virtualenvwrapper.sh"'

# Ruby
export PATH="$PATH:$HOME/.rvm/bin"
alias ra='source "$HOME/.rvm/scripts/rvm" ; source "$HOME/.rvm/scripts/completion"'

# Git
alias ga='source "$HOME/.git-activate.sh"'

# Modern times
#eval $(direnv hook bash)

# Docker
alias da='source "$HOME/.docker-activate.sh"'

# SSH
_compssh () {
    cur=${COMP_WORDS[COMP_CWORD]};
    COMPREPLY=($(compgen -W '$(cat ${HOME}/.ssh/config | grep "^Host\b" - | sed -e "s/Host //")' -- $cur))
}
complete -F _compssh ssh

# Aliases all and other custom (private) aliases
[[ -f "/etc/profile.d/aliases-loader.sh" ]] && source "/etc/profile.d/aliases-loader.sh"
[[ -f "$HOME/.local_bashrc" ]] && source "$HOME/.local_bashrc"

# EOF
