# User specific aliases and functions
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias vi='vim'

if [[ "$OSTYPE" == "linux-gnu" ]]
then
    alias ls='ls --color=tty'
    alias ll='ls -la --color=tty'
    alias l.='ls -d .* --color=tty'
    alias which='alias | /usr/bin/which'
else
    alias ls='ls -G'
    alias ll='ls -la -G'
    alias l.='ls -d .* -G'
fi

alias egrep="egrep --color"
alias grep="grep --color"
#alias rz='lrz -br'
#alias sz='lsz -br'

# Tahoe
alias t='tahoe -d $HOME/.tahoe'
alias tw='tahoe -d $HOME/.tahoe webopen'
alias tp='tahoe -d $HOME/.tahoe-private'
alias tpw='tahoe -d $HOME/.tahoe-private webopen'

export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
export SYSTERM="linux"
export SYSFONT="lat1u-16"
export LC_COLLATE="POSIX"
export LS_COLORS="$LS_COLORS:di=01;33:*.rpm=01;31"
export LS_COLORS=$(echo $LS_COLORS | sed 's/00;31/01;31/g')
export HOSTNAME=$(echo "${HOSTNAME}" | cut -d. -f 1)
export EDITOR="vim"
export HISTTIMEFORMAT="%a %b %d %H:%M:%S %Z %Y - "
export HISTFILESIZE=99999
export HISTSIZE=99999

export PATH="$PATH:/opt/local/bin:/opt/local/sbin"
export PATH="$PATH:$HOME/Dropbox/stockrt/scripts"
export PATH="$PATH:$HOME/node_modules/.bin"
export PATH="$PATH:$HOME/adt-bundle/sdk/tools"
export PATH="$PATH:$HOME/adt-bundle/sdk/platform-tools"
export PATH="$PATH:/usr/local/mysql/bin"
export PATH="/usr/python27/bin:/usr/python26/bin:$PATH"

inversor() {
    # Dividir a saida em linhas invertidas:
    rev | while read linha; do
        # Dividir cada linha invertida em colunas:
        for cn in `echo $linha`; do
            # Mostrar coluna, desinvertendo suas letras
            echo -n `echo $cn | rev`
            # Dar espaco
            echo -n " "
        done

        # pular linha
        echo ""
    done
}

# Python
alias python-activate='source "$HOME/.virtualenvs/venv/bin/activate" ; source "$HOME/.virtualenvs/venv/bin/virtualenvwrapper.sh"'
#[[ -f "$HOME/.virtualenvs/venv/bin/activate" ]] && source "$HOME/.virtualenvs/venv/bin/activate"
#[[ -f "$HOME/.virtualenvs/venv/bin/virtualenvwrapper.sh" ]] && source "$HOME/.virtualenvs/venv/bin/virtualenvwrapper.sh"

# Ruby
export rvm_path="$HOME/.rvm"
[[ -s "$rvm_path/scripts/rvm" ]] && source "$rvm_path/scripts/rvm"
[[ -f "$rvm_path/scripts/completion" ]] && source "$rvm_path/scripts/completion"

# SSH
_compssh () {
    cur=${COMP_WORDS[COMP_CWORD]};
    COMPREPLY=($(compgen -W '$(cat ${HOME}/.ssh/config | grep "^Host\b" - | sed -e "s/Host //")' -- $cur))
}
complete -F _compssh ssh

# Git
if [[ -f "$HOME/.git-completion.bash" ]]
then
    source "$HOME/.git-completion.bash"
fi
if [[ -f "$HOME/.git-prompt.sh" ]]
then
    source "$HOME/.git-prompt.sh"
    export PS1='\t \u@\h \w$(__git_ps1 " (%s)") \$ '
    export GIT_PS1_DESCRIBE_STYLE="branch"
    export GIT_PS1_SHOWCOLORHINTS="true"
    export GIT_PS1_SHOWDIRTYSTATE="true"
    export GIT_PS1_SHOWSTASHSTATE="true"
    export GIT_PS1_SHOWUNTRACKEDFILES="true"
    export GIT_PS1_SHOWUPSTREAM="auto verbose"
fi
